databases:
  - name: projects_api_postgres
    databaseName: projects_api_production
    user: projects_api

services:
  - type: web
    name: projects-api
    env: ruby
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: projects_api_postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
